from pathlib import Path
import sys
root=Path(sys.argv[1])
def rep(path, pairs):
    p=root/path; s=p.read_text()
    for a,b in pairs: s=s.replace(a,b)
    p.write_text(s)
rep('App/AppRootView.swift',[( 'Text("Initializing map and location test environment…")','Text("جارٍ تهيئة الخريطة وبيئة اختبار الموقع…")')])
rep('Models/RuntimeModels.swift',[( 'case appWiFi = "App Mode"','case appWiFi = "وضع التطبيق"'),('case thirdParty = "Third-party Proxy"','case thirdParty = "بروكسي خارجي"'),('return "Local on-device proxy · current Wi‑Fi"','return "بروكسي محلي داخل الجهاز · شبكة Wi‑Fi الحالية"')])
rep('App/AppStore.swift',[( '"Not checked"','"لم يتم الفحص"'),('"Initial setup completed"','"اكتمل الإعداد الأولي"'),('"Setup was reset"','"تمت إعادة ضبط الإعداد"'),('"Selected %.6f, %.6f"','"تم اختيار %.6f, %.6f"'),('"Saved to Favorites"','"تم الحفظ في المفضلة"'),('"Checking…"','"جارٍ الفحص…"'),('"Select a location first"','"اختر موقعًا أولًا"'),('"Virtual location enabled"','"تم تفعيل الموقع الافتراضي"'),('"Virtual location disabled"','"تم إيقاف الموقع الافتراضي"')])
rep('Features/Map/MapHomeView.swift',[( '"Save Favorite"','"حفظ في المفضلة"'),('"Name"','"الاسم"'),('"Save"','"حفظ"'),('"Saved location"','"موقع محفوظ"'),('"Cancel"','"إلغاء"'),('"Search location"','"ابحث عن موقع"'),('"Place"','"مكان"'),('"Virtual location active"','"الموقع الافتراضي مفعّل"'),('"Virtual location inactive"','"الموقع الافتراضي غير مفعّل"'),('"Selected location"','"الموقع المحدد"'),('"Accuracy"','"الدقة"'),('"Update Location"','"تحديث الموقع"'),('"Enable Location"','"تفعيل الموقع"'),('"Tap the map, drag to an area, or search for a place to select a test location."','"اضغط على الخريطة أو حرّكها أو ابحث عن مكان لاختيار موقع الاختبار."'),('"No mode"','"لا يوجد وضع"'),('"Logs"','"السجلات"'),('"Current location"','"موقعي الحالي"'),('"Could not read current location"','"تعذر قراءة موقعك الحالي"')])
rep('Features/Settings/SettingsScreen.swift',[( 'Section("Runtime")','Section("التشغيل")'),('"Mode"','"الوضع"'),('"Not selected"','"غير محدد"'),('"Client"','"العميل"'),('"Run environment check"','"فحص البيئة"'),('Section("Location")','Section("الموقع")'),('"Accuracy"','"الدقة"'),('"Motion simulation"','"محاكاة الحركة"'),('"Map coordinates"','"نظام إحداثيات الخريطة"'),('Section("App Mode")','Section("وضع التطبيق")'),('"Proxy"','"البروكسي"'),('"Open certificate page"','"فتح صفحة الشهادة"'),('"CA installed"','"تم تثبيت الشهادة"'),('"CA trusted"','"الشهادة موثوقة"'),('"Wi‑Fi proxy configured"','"تم إعداد بروكسي Wi‑Fi"'),('Section("Support")','Section("الدعم")'),('"Diagnostics & Logs"','"التشخيص والسجلات"'),('"Copy diagnostic report"','"نسخ تقرير التشخيص"'),('"Diagnostic report copied"','"تم نسخ تقرير التشخيص"'),('Section("Setup")','Section("الإعداد")'),('"Run setup again"','"إعادة الإعداد"'),('Section("About")','Section("حول")'),('"App"','"التطبيق"'),('"Version"','"الإصدار"'),('"Independent clean-room implementation for location-service research, app development testing, and QA validation."','"تنفيذ مستقل مخصص لأبحاث خدمات الموقع واختبار التطبيقات والتحقق من الجودة على الأجهزة والبيئات المصرح بها."'),('"Settings"','"الإعدادات"'),('"Done"','"تم"'),('"Run setup again?"','"إعادة الإعداد؟"'),('"Reset setup"','"إعادة ضبط الإعداد"'),('"Cancel"','"إلغاء"')])
rep('Features/Setup/SetupFlowView.swift',[( '"Choose a test mode"','"اختر وضع الاختبار"'),('"You can change this later in Settings."','"يمكنك تغيير هذا لاحقًا من الإعدادات."'),('"Use only on devices, networks, and software environments you own or are authorized to test."','"استخدم التطبيق فقط على الأجهزة والشبكات والبيئات التي تملكها أو لديك تصريح لاختبارها."'),('title: "App Mode"','title: "وضع التطبيق"'),('text: "Runs the proxy engine inside GeoShift and uses the current Wi‑Fi manual HTTP proxy path."','text: "يشغّل محرك البروكسي داخل GeoShift ويستخدم إعداد البروكسي اليدوي لشبكة Wi‑Fi الحالية."'),('Section("1 · Local proxy")','Section("1 · البروكسي المحلي")'),('"Proxy address"','"عنوان البروكسي"'),('"Open proxy status page"','"فتح صفحة حالة البروكسي"'),('"Check embedded proxy"','"فحص البروكسي المدمج"'),('Section("2 · Install and trust CA")','Section("2 · تثبيت الشهادة والثقة بها")'),('"Download local CA certificate"','"تنزيل شهادة CA المحلية"'),('"Certificate installed"','"تم تثبيت الشهادة"'),('"Full trust enabled"','"تم تفعيل الثقة الكاملة"'),('"After installation: Settings → General → About → Certificate Trust Settings → enable full trust for the GeoShift test CA."','"بعد التثبيت: الإعدادات ← عام ← حول ← إعدادات الثقة بالشهادات ← فعّل الثقة الكاملة لشهادة GeoShift."'),('Section("3 · Wi‑Fi manual HTTP proxy")','Section("3 · بروكسي HTTP يدوي لشبكة Wi‑Fi")'),('"Manual proxy configured"','"تم إعداد البروكسي اليدوي"'),('"Configure the current Wi‑Fi network manual HTTP proxy to the iPhone’s Wi‑Fi address on port 8888. App Mode covers only that Wi‑Fi path."','"اضبط البروكسي اليدوي لشبكة Wi‑Fi الحالية على عنوان Wi‑Fi الخاص بالآيفون والمنفذ 8888. وضع التطبيق يعمل على مسار Wi‑Fi هذا فقط."'),('"Finish setup"','"إنهاء الإعداد"'),('"Choose another mode"','"اختيار وضع آخر"'),('title: "Third-party Proxy Mode"','title: "وضع البروكسي الخارجي"'),('text: "GeoShift manages the selected coordinates. Your proxy client owns VPN/proxy, HTTPS decryption, certificate trust, and the WLOC module."','text: "يدير GeoShift الإحداثيات المحددة، بينما يتولى تطبيق البروكسي الخارجي الـVPN/البروكسي وفك HTTPS والثقة بالشهادة ووحدة WLOC."'),('Section("1 · Choose client")','Section("1 · اختر تطبيق البروكسي")'),('"Proxy client"','"تطبيق البروكسي"'),('Section("2 · Enable module")','Section("2 · تفعيل الوحدة")'),('"The app expects the local configuration contract at /wloc-settings/save for query, save, and clear."','"يتوقع التطبيق واجهة الإعداد المحلية /wloc-settings/save للاستعلام والحفظ والمسح."'),('Section("3 · Connection check")','Section("3 · فحص الاتصال")'),('"Checking…"','"جارٍ الفحص…"'),('"Check module connection"','"فحص اتصال الوحدة"'),('"Ready"','"جاهز"'),('"Connected · inactive"','"متصل · غير مفعّل"'),('"Unavailable"','"غير متاح"'),('"Checking"','"جارٍ الفحص"')])
rep('Features/Favorites/FavoritesScreen.swift',[( '"No favorites yet"','"لا توجد مواقع مفضلة بعد"'),('"Delete"','"حذف"'),('"Rename"','"إعادة تسمية"'),('"Favorites"','"المفضلة"'),('"Done"','"تم"'),('"Rename Favorite"','"إعادة تسمية المفضلة"'),('"Name"','"الاسم"'),('"Save"','"حفظ"'),('"Cancel"','"إلغاء"')])
rep('Features/Settings/DiagnosticsScreen.swift',[( 'Section("Environment")','Section("البيئة")'),('"Mode"','"الوضع"'),('"None"','"لا يوجد"'),('"Provider"','"المزوّد"'),('"Run check"','"تشغيل الفحص"'),('Section("Local path")','Section("المسار المحلي")'),('"CA installed"','"الشهادة مثبتة"'),('"CA trusted"','"الشهادة موثوقة"'),('"Manual Wi‑Fi proxy"','"بروكسي Wi‑Fi يدوي"'),('Section("Tools")','Section("الأدوات")'),('"Copy logs"','"نسخ السجلات"'),('"Copy sanitized report"','"نسخ تقرير منقح"'),('"Clear logs"','"مسح السجلات"'),('Section("Runtime logs")','Section("سجلات التشغيل")'),('"No runtime events"','"لا توجد أحداث تشغيل"'),('"Diagnostics"','"التشخيص"'),('"Done"','"تم"'),('"Copied"','"تم النسخ"'),('"OK"','"حسنًا"')])
rep('Services/LocationProviders.swift',[( '"Invalid provider URL."','"رابط المزوّد غير صالح."'),('"Provider returned an unexpected response."','"أعاد المزوّد استجابة غير متوقعة."'),('let name = "WLOC Module"','let name = "وحدة WLOC"'),('"Module connected; virtual location is active."','"الوحدة متصلة والموقع الافتراضي مفعّل."'),('"Module connected; no saved coordinate."','"الوحدة متصلة ولا توجد إحداثيات محفوظة."'),('"Module connected; virtual location is inactive."','"الوحدة متصلة والموقع الافتراضي غير مفعّل."'),('"The module rejected the coordinate."','"رفضت الوحدة الإحداثيات."'),('"Unable to clear the saved coordinate."','"تعذر مسح الإحداثيات المحفوظة."'),('let name = "Embedded On-device Proxy"','let name = "البروكسي المدمج على الجهاز"')])
# Force RTL on root view hierarchy
p=root/'App/AppRootView.swift'; s=p.read_text(); s=s.replace('        .task {','        .environment(\\.layoutDirection, .rightToLeft)\n        .task {'); p.write_text(s)
print('Arabic UI patch applied')