from pathlib import Path
import sys
root=Path(sys.argv[1])
def rw(rel,fn):
 p=root/rel; s=p.read_text(); p.write_text(fn(s))
def ins(s,needle,text):
 return s if text.strip() in s else s.replace(needle,text+needle)
# Go: proof-of-path HTTPS verification, request counters, reset CA.
def patch_main(s):
 s=s.replace('Motion   bool\n}', 'Motion   bool\n\tRequests uint64\n\tPatched uint64\n}')
 if 'req.URL.Path == "/geoshift-verify"' not in s:
  s=s.replace('func (p *proxyServer) handleWlocHTTPS(w http.ResponseWriter, req *http.Request, host string) {', '''func (p *proxyServer) handleWlocHTTPS(w http.ResponseWriter, req *http.Request, host string) {\n\tif req.URL.Path == "/geoshift-verify" {\n\t\tstate.Lock(); state.Requests++; state.Unlock()\n\t\tw.Header().Set("Content-Type", "application/json")\n\t\tw.Header().Set("Cache-Control", "no-store")\n\t\tio.WriteString(w, `{"success":true,"proxy":"GeoShiftCore"}`)\n\t\treturn\n\t}\n\tstate.Lock(); state.Requests++; state.Unlock()''')
 s=s.replace('''if patched, ok := patchEnvelope(body, cfg); ok {\n\t\t\t\tbody = patched\n\t\t\t}''','''if patched, ok := patchEnvelope(body, cfg); ok {\n\t\t\t\tbody = patched\n\t\t\t\tstate.Lock(); state.Patched++; state.Unlock()\n\t\t\t}''')
 return s
rw('Core/main.go',patch_main)
def patch_bridge(s):
 s=s.replace('"motion":   state.Motion,', '"motion":   state.Motion,\n\t\t"requests": state.Requests,\n\t\t"patched": state.Patched,')
 if 'geoshift_core_reset_ca' not in s:
  s=s.replace('//export geoshift_core_free', '''//export geoshift_core_reset_ca\nfunc geoshift_core_reset_ca(storageDir *C.char) C.int {\n\t_ = geoshift_core_stop()\n\tdir := C.GoString(storageDir)\n\tif dir == "" { return 1 }\n\t_ = os.Remove(filepath.Join(dir, "geoshift-ca.pem"))\n\t_ = os.Remove(filepath.Join(dir, "geoshift-ca-key.pem"))\n\treturn 0\n}\n\n//export geoshift_core_free''')
 return s
rw('Core/bridge.go',patch_bridge)
# Silent-audio keepalive, mirroring the reference runtime behavior without copying its source.
(root/'Services/BackgroundKeepAlive.swift').write_text(r'''import AVFoundation\nimport UIKit\nfinal class BackgroundKeepAlive {\n static let shared = BackgroundKeepAlive(); private var engine:AVAudioEngine?; private var player:AVAudioPlayerNode?; private var active=false\n private init() {}\n func start(){ guard !active else{return}; do { let s=AVAudioSession.sharedInstance(); try s.setCategory(.playback,mode:.default,options:.mixWithOthers); try s.setActive(true); let e=AVAudioEngine(); let p=AVAudioPlayerNode(); e.attach(p); guard let f=AVAudioFormat(standardFormatWithSampleRate:44100,channels:1), let b=AVAudioPCMBuffer(pcmFormat:f,frameCapacity:132300) else{return}; b.frameLength=b.frameCapacity; e.connect(p,to:e.mainMixerNode,format:f); try e.start(); p.scheduleBuffer(b,at:nil,options:.loops); p.play(); engine=e; player=p; active=true; UIApplication.shared.isIdleTimerDisabled=true } catch {} }\n func stop(){ guard active else{return}; active=false; player?.stop(); engine?.stop(); player=nil; engine=nil; UIApplication.shared.isIdleTimerDisabled=false; try? AVAudioSession.sharedInstance().setActive(false,options:.notifyOthersOnDeactivation) }\n}\n''')
(root/'Services/CertificateTrustVerifier.swift').write_text(r'''import Foundation\nimport Security\nenum CertificateTrustVerifier {\n static func isTrusted(pem:String)->Bool { guard let a=pem.range(of:"-----BEGIN CERTIFICATE-----"),let b=pem.range(of:"-----END CERTIFICATE-----") else{return false}; let body=pem[a.upperBound..<b.lowerBound].components(separatedBy:.whitespacesAndNewlines).joined(); guard let d=Data(base64Encoded:body),let c=SecCertificateCreateWithData(nil,d as CFData) else{return false}; var t:SecTrust?; guard SecTrustCreateWithCertificates(c,SecPolicyCreateBasicX509(),&t)==errSecSuccess,let t else{return false}; SecTrustSetAnchorCertificatesOnly(t,false); return SecTrustEvaluateWithError(t,nil) }\n}\n''')
# Embedded manager: CA exposure/reset + keepalive + richer state.
p=root/'Services/EmbeddedCoreManager.swift'; s=p.read_text()
s=s.replace('@_silgen_name("geoshift_core_free")', '@_silgen_name("geoshift_core_cert_pem") private func core_cert_pem() -> UnsafeMutablePointer<CChar>?\n@_silgen_name("geoshift_core_reset_ca") private func core_reset_ca(_ storageDir: UnsafePointer<CChar>) -> Int32\n@_silgen_name("geoshift_core_free")')
s=s.replace('RuntimeLogStore.shared.add(.success, "Core", "Embedded proxy started on port 8888")', 'BackgroundKeepAlive.shared.start()\n        RuntimeLogStore.shared.add(.success, "Core", "Embedded proxy started on port 8888")')
s=s.replace('_ = core_stop()\n        RuntimeLogStore.shared.add', '_ = core_stop()\n        BackgroundKeepAlive.shared.stop()\n        RuntimeLogStore.shared.add')
if 'func certificatePEM()' not in s:
 s=s.replace('    func status() -> ProviderStatus {', '''    func certificatePEM() -> String? { guard let p=core_cert_pem() else{return nil}; defer{core_free(UnsafeMutableRawPointer(p))}; return String(cString:p) }\n    func resetCertificate() throws { let rc=storageDirectory.withCString{core_reset_ca($0)}; guard rc==0 else{throw LocationProviderError.unavailable("تعذر إعادة ضبط الشهادة")}; try start() }\n\n    func status() -> ProviderStatus {''')
s=s.replace('let running: Bool', 'let requests: UInt64?\n        let patched: UInt64?\n        let running: Bool')
p.write_text(s)
# Replace local provider check with a real HTTPS proof that must traverse the manual proxy and trusted CA.
p=root/'Services/LocationProviders.swift'; s=p.read_text(); start=s.index('final class LocalProxyProvider:'); s=s[:start]+r'''final class LocalProxyProvider: LocationTestProvider {\n    let name = "البروكسي المدمج على الجهاز"\n    private let core = EmbeddedCoreManager.shared\n    func check() async -> ProviderStatus {\n        do {\n            if !core.isRunning { try core.start() }\n            let runtime=core.status()\n            guard let pem=core.certificatePEM(), CertificateTrustVerifier.isTrusted(pem:pem) else { return .init(health:.unavailable,detail:"شهادة GeoShift غير موثوقة بالكامل. ثبّتها ثم فعّل الثقة الكاملة من إعدادات iOS.",activePoint:runtime.activePoint,accuracy:runtime.accuracy) }\n            var req=URLRequest(url:URL(string:"https://gs-loc.apple.com/geoshift-verify?nonce=\\(UUID().uuidString)")!); req.timeoutInterval=7; req.cachePolicy=.reloadIgnoringLocalAndRemoteCacheData\n            let cfg=URLSessionConfiguration.ephemeral; cfg.requestCachePolicy=.reloadIgnoringLocalAndRemoteCacheData\n            let (data,res)=try await URLSession(configuration:cfg).data(for:req)\n            guard let h=res as? HTTPURLResponse,h.statusCode==200,let o=try? JSONSerialization.jsonObject(with:data) as? [String:Any],o["success"] as? Bool==true,o["proxy"] as? String=="GeoShiftCore" else { return .init(health:.unavailable,detail:"الشهادة موثوقة لكن HTTPS لا يمر عبر GeoShift. اضبط بروكسي Wi‑Fi يدويًا على عنوان الآيفون والمنفذ 8888.",activePoint:runtime.activePoint,accuracy:runtime.accuracy) }\n            return .init(health:runtime.activePoint == nil ? .inactive:.ready,detail:runtime.activePoint == nil ? "البيئة جاهزة والبروكسي والشهادة يعملان. الموقع الافتراضي متوقف.":"البيئة جاهزة والموقع الافتراضي مفعّل.",activePoint:runtime.activePoint,accuracy:runtime.accuracy)\n        } catch { return .init(health:.unavailable,detail:"فشل فحص مسار البروكسي: \\(error.localizedDescription)",activePoint:nil,accuracy:nil) }\n    }\n    func apply(point:GeoPoint,accuracy:Double,motion:Bool) async throws { if !core.isRunning{try core.start()}; core.set(point:point,accuracy:accuracy,motion:motion) }\n    func clear() async throws { if !core.isRunning{try core.start()}; core.set(point:nil,accuracy:25,motion:false) }\n}\n'''.replace('\\n','\n')
p.write_text(s)
# App state: don't confuse environment-ready with active coordinate; add cert reset.
p=root/'App/AppStore.swift'; s=p.read_text(); s=s.replace('isVirtualLocationActive = providerStatus.health == .ready', 'isVirtualLocationActive = providerStatus.activePoint != nil')
if 'resetLocalCertificate' not in s:
 s=s.replace('\n    func disableVirtualLocation() async {', '''\n    func resetLocalCertificate() async { do { try EmbeddedCoreManager.shared.resetCertificate(); toast="تم إنشاء شهادة جديدة. ثبّتها ووثّقها من جديد."; providerStatus=.init(health:.unavailable,detail:"تحتاج الشهادة الجديدة إلى التثبيت والثقة الكاملة.",activePoint:nil,accuracy:nil) } catch { toast=error.localizedDescription } }\n\n    func disableVirtualLocation() async {''')
p.write_text(s)
# Map-center selection on drag, like the reference UX.
rw('Features/Map/MapHomeView.swift',lambda s:s.replace('onCenterChanged: { c, meters in visibleRegion = .init(center: c, latitudinalMeters: meters, longitudinalMeters: meters) }','onCenterChanged: { c, meters in visibleRegion = .init(center: c, latitudinalMeters: meters, longitudinalMeters: meters); store.selectMapPoint(GeoPoint(c)); reverseGeocode(c) }'))
# Background audio declaration + executable key.
p=root/'Resources/Info.plist'; s=p.read_text(); s=s.replace('<key>CFBundleDisplayName</key><string>GeoShift</string>','<key>CFBundleDisplayName</key><string>GeoShift</string>\n<key>CFBundleExecutable</key><string>$(EXECUTABLE_NAME)</string>'); s=s.replace('</dict></plist>','<key>UIBackgroundModes</key><array><string>audio</string></array>\n</dict></plist>'); p.write_text(s)
# Build/version + Xcode 16 fixes.
rw('project.yml',lambda s:s.replace('MARKETING_VERSION: "2.1.0"','MARKETING_VERSION: "3.0.0"').replace('CURRENT_PROJECT_VERSION: "21"','CURRENT_PROJECT_VERSION: "30"'))
rw('Services/RealtimeLocationService.swift',lambda s:s.replace('final class RealtimeLocationService: NSObject, ObservableObject, CLLocationManagerDelegate {','final class RealtimeLocationService: NSObject, ObservableObject, @preconcurrency CLLocationManagerDelegate {'))
rw('Models/GeoModels.swift',lambda s:s.replace('''        case .gcj02:\n            let wgs = CoordinateConverter.gcj02ToWGS84(mapPoint)\n            self.wgs84 = wgs\n            self.gcj02 = mapPoint''','''        case .gcj02:\n            let wgs = CoordinateConverter.gcj02ToWGS84(mapPoint)\n            self.init(wgs84: wgs)\n            self.gcj02 = mapPoint'''))
rw('Features/Settings/DiagnosticsScreen.swift',lambda s:s.replace('    static func make(store: AppStore) -> String {','    @MainActor\n    static func make(store: AppStore) -> String {'))
print('GeoShift parity v3 patches applied')
